# Generated by Django 3.0.5 on 2021-01-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='DataSignification',
        ),
    ]
